# Generated by Django 4.2.13 on 2026-02-04 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("location_found", models.CharField(blank=True, max_length=255)),
                ("date_found", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("FOUND", "Found"), ("CLAIMED", "Claimed")],
                        db_index=True,
                        default="FOUND",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-date_found", "-created_at"],},
        ),
        migrations.CreateModel(
            name="ItemImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="item_images/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="inventory.item",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["status"], name="inventory_i_status_25f563_idx"),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["date_found"], name="inventory_i_date_fo_bc0fa4_idx"
            ),
        ),
    ]
