# Generated by Django 4.2.13 on 2026-02-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_item_claimed_at_item_claimed_by_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("ELECTRONICS", "Electronics"),
                    ("BAGS_AND_CARRY", "Bags and Carry"),
                    ("SPORTS_AND_CLOTHING", "Sports and clothing"),
                    ("BOTTLES_AND_CONTAINERS", "Bottles and containers"),
                    ("DOCUMENTS_AND_IDS", "Documents and Id's"),
                    ("NOTEBOOKS_AND_BOOKS", "Notebooks/books"),
                    ("OTHER_MISC", "Other/Misc"),
                ],
                db_index=True,
                default="OTHER_MISC",
                max_length=40,
            ),
        ),
    ]
