# Generated by Django 4.2.13 on 2026-02-06 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_item_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "claimant_name",
                    models.CharField(
                        help_text="Name of person claiming this item", max_length=255
                    ),
                ),
                ("claimed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="inventory.item",
                    ),
                ),
            ],
            options={
                "ordering": ["-claimed_at"],
                "indexes": [
                    models.Index(
                        fields=["item", "-claimed_at"],
                        name="inventory_c_item_id_b3d1cb_idx",
                    )
                ],
            },
        ),
    ]
