# Generated by Django 4.2.13 on 2026-08-24 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_add_collected_status"),
    ]

    operations = [
        migrations.DeleteModel(name="MagicLinkRequest",),
    ]
